spring.application.name=webpilot-ai

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/webpilot
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.data.redis.host=localhost
#spring.data.redis.port=6382