spring.application.name=webpilot-ai

server.port=${SERVER_PORT:8084}

#############################################
# DATABASE
#############################################

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/webpilot}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

#############################################
# JPA
#############################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#############################################
# JWT
#############################################

jwt.secret=${JWT_SECRET:webpilotsecretkeywebpilotsecretkeywebpilotsecretkey}
jwt.expiration=86400000

#############################################
# AI
#############################################

ai.provider=openai
ai.model=${AI_MODEL:gpt-4o-mini}
ai.api.key=${OPENAI_API_KEY}

#############################################
# PLAYWRIGHT
#############################################

browser.headless=true

#############################################
# LOGGING
#############################################

logging.level.org.springframework.security=INFO
logging.level.com.webpilot=DEBUG

#############################################
# REDIS
#############################################

# spring.data.redis.host=${REDIS_HOST:localhost}
# spring.data.redis.port=${REDIS_PORT:6379}